# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'Google/Analytics'

target 'Example Project' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example Project

  target 'Example ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Example ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
